Completed task
akonovalovdev/task-encoding pull request #1
Opened 2023-11-30 18:52 UTC by akonovalovdev

so good

2023-12-02 13:55 UTC, akonovalovdev commented
<img width="956" alt="image" src="https://github.com/akonovalovdev/task-encoding/assets/128315677/5774cffc-27e0-4059-9126-d6172a21ccbc">
@robotomize скажи пожалуйста, ты пока не писал комментарии?

Может опять я их просто не вижу

2023-12-04 11:40 UTC, robotomize requested changes
Отличная работа, есть пара мелочей с артефактами под контролем версии, их лучше удалить

2023-12-04 11:40 UTC, robotomize commented on jsonOutput.json
> +{
Все артефакты работы программы, json/yaml лучше не добавляь под контроль версии и убрать

2023-12-04 11:40 UTC, robotomize commented on encoding/encoding.go
> +	j.DockerCompose = &models.DockerCompose{}
В целом это не ошибка, но мы можем прокинуть в Unmarshal указатель на указатель и не инициализировать указатель на DockerCompose, резльтат будет тот же

json.Unmarshal(jsonFile, &j.DockerCompose). В функции yaml аналогично

2023-12-04 15:17 UTC, robotomize approved these changes
Отлично! Принимается

Если вам будет интересно или скучно ждать следующего спринта отметил парочку топиков над которыми можно дополнительно поработать и углубить знания

- Ошибки можно оборачивать с помощью fmt.Errorf("text error: %w", err). Тогда ошибки обрастают контекстом. Это могает быстрее понять где произошла ошибка. Они будут выстраиваться в цепочку, которую наверху можно будет вывести
- У сериализаторов есть возможность работать в стриминговом режиме, например json.NewDecoder, json.NewEncoder. Можно посмотреть, что они принимают на вход. Для работы с потоком или файлами это может быть полезно в плане сокращения кода, удобства, а также затрат по памяти. Это может быть полезно, когда файлы сериализации большие.

2023-12-07 11:34 UTC, merged